### PR TITLE
Updated README.md to look more friendly

### PR DESCRIPTION
**Pull request by FelipeNBrito**
Nice lib by the way. It really saved me some time :+1:

### CODE REVIEW

**Comment by FelipeNBrito** [comment]
Check out how it looks like: https://github.com/FelipeNBrito/validate-password/blob/a6fd9b546fe4d07a0e4009aa7a575599266ef6db/README.md

**Comment by mndewitt** [comment]
This looks great, thanks Felipe!  I'm fine with [MIT](http://choosealicense.com/licenses/mit/), would you mind just adding that and I can merge and give you the credit?

**Comment by FelipeNBrito** [comment]
Sure, I'll do it in a couple minutes.

**Comment by FelipeNBrito** [comment]
Just finished updating to the MIT license

https://github.com/FelipeNBrito/validate-password/tree/patch-1

**Comment by mndewitt** [comment]
Thanks again!

**Pull request merged**
