### PR TITLE
Fixing issue where code cannot be imported in a Node application.

### PR DESCRIPTION
**Pull request by davidadas**
Just an FYI, your code cannot be `require`d in the current version of Node.

### CODE REVIEW

**Comment by mndewitt** [comment]
Thanks for the heads up, and contribution David!  A couple of things I want to cross check, which I can do later or you can if you want - do the builds need to be updated?  Do we need the files in the dist folder to be index.js (I assume not...).  But maybe something in the npm scripts needs to change?  I can't tell from just looking.

You could also bump the patch version in the package.json, and this would be good to go.

**Comment by davidadas** [comment]
I do not...think the builds need to be updated, nor do the files in the dist folder.  It's just that the current version of Node (at least) requires that the root folder have an index.js file in it.  I could not use the package without changing that.  Once I did, though, it immediately recognized the package.

Still, might want to double check that to confirm.  

In the meantime, I will update the version.

**Comment by davidadas** [comment]
Hrmm, maybe they do need to be updated in dist.  Might need your help to figure that out.  I'm used to a slightly different structure :(

**Comment by mndewitt** [comment]
Cool.  I think it's fine to leave the files in /dist as validate-password.js.  For the build, try running `npm run build` and see if there are any errors.  I'd think you would need to change the build scripts in the package.json to something like:

```
  "scripts": {
    "build": "npm run build:max && npm run build:min",
    "build:max": "browserify --standalone ValidatePassword --outfile ./dist/validate-password.js",
    "build:min": "browserify --transform [uglifyify] --standalone ValidatePassword --outfile ./dist/validate-password.min.js",
    "test": "./node_modules/mocha/bin/mocha *.test.js --reporter spec"
  }
```
Maybe?  Just try the build and see if there are any errors.

**Comment by mndewitt** [comment]
Alright, this should work for the updates to package.json:

```
  "scripts": {
    "build": "npm run build:max && npm run build:min",
    "build:max": "browserify index --standalone ValidatePassword --outfile ./dist/validate-password.js",
    "build:min": "browserify index --transform [uglifyify] --standalone ValidatePassword --outfile ./dist/validate-password.min.js",
    "test": "./node_modules/mocha/bin/mocha *.test.js --reporter spec"
  }
```

you may need to install browserify if you don't already have that installed: `npm install -g browserify`.  If you can just update that this is good to go and I can give you the credit.  Thanks!

**Comment by davidadas** [comment]
Awesome!  I will fix it up shortly.  Sorry for the delayed responses -- busy startup environment :)  Will jump on it soon.

**Comment by bluesockets** [comment]
+1

**Comment by mndewitt** [comment]
@bluesockets this should be fixed in version 1.0.4

**Pull request closed without merging**
